INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bichón Boloñés','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bichón Maltés','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Chihuahua','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Chihuahua adult standing','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Chihuahua smooth coat','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pequeño Brabanzón','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pequeño Perro Ruso','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Crestado Chino','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pomerano adulto de pie','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pomerano','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel Continental Enano','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel Japonés','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier de Juguete Inglés (Negro y Fuego)','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Sedoso Australiano','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Yorkshire Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Affenpinscher','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Basset Leonado de Bretaña','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bedlington Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bichón Frisé','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bichón Habanero','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Border Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Boston Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco de Auvernia','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bull Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cairn Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cavalier King Charles Spaniel','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Coton de Tulear','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Dachshund','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Dandie Dinmont Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Fox Terrier de Pelo Duro','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Fox Terrier de Pelo Liso','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Grifón Belga','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Grifón de Bruselas','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Jack Russell Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('King Charles Spaniel','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Lakeland Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Lhasa Apso','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Lundehund Noruego adulto sobre el césped','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Lundehund Noruego','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Mudi','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor de los Pirineos de Cara Rasa','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor de los Pirineos','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor de Shetland','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pekinés','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pequeño Lebrel Italiano','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pequeño Perro León','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Granja Danés y Sueco','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Smous Holandés','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pinscher Miniatura','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Podenco Portugués','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pug','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pumi','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Schipperke','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Schnauzer Miniatura','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Shiba','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Shih Tzu','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Skye Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel Tibetano','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spitz de los Visigodos','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spitz Japonés','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Australiano','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Brasileño','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Cazador Alemán','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Checo','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier de Manchester','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier de Norfolk','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier de Norwich','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier de Sealyham','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier del Reverendo Russell','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Escocés','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Galés','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Japonés','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Volpino Italiano','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('West Highland White Terrier','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Whippet','pequenio','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Airedale Terrier','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Alaskan Malamute','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('American Staffordshire Terrier','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Ariegeois','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Barbet','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Basenji','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Basset Artesiano de Normandía','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Basset Azul de Gascuña','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Beagle','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Beagle-Harrier','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bearded Collie','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Border Collie','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Boyero de las Ardenas','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco del Ariege','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco del Borbonesado','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco Eslovaco de Pelo Duro','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco Francés - Tipo Pirineos','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco Húngaro de Pelo Corto','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco Saint-Germain','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Briquet Grifón Vendeano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Buhund Noruego','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Buhund Noruego adulto','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bulldog Francés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bulldog Inglés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Caniche','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cazador de Alces Noruego Negro','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Chow Chow','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cirneco del Etna','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cocker Spaniel Americano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cocker Spaniel Inglés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Collie de Pelo Corto','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Collie de Pelo Largo','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Dachsbracke de los Alpes','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Dobermann','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Drever','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Eurásico','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Foxhound Americano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gascón Saintongeois','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gran Basset Grifón Vendeano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Grifón Azul de Gascuña','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Grifón de Muestra de Pelo Duro','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Grifón del Nivernais','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Grifón Leonado de Bretaña','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Harrier','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Hokkaido','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Husky Siberiano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Irish Glen of Imaal Terrier','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Jindo Coreano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Kai','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Kelpie Australiano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Kerry Blue Terrier','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Kishu','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Kromfohrländer','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Laika de Siberia Occidental','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Laika de Siberia Oriental','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Laika Ruso-Europeo','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Ovejero Belga','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor Australiano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor Australiano de Cola Corta','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor Bergamasco','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor de Karst','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor de Picardía','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor Finlandés de Laponia','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor Islandés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor Polaco de las Llanuras','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pequeño Basset Grifón Vendeano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pequeño Münsterländer','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pequeño Sabueso Azul de Gascuña','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perdiguero Alemán','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perdiguero Frisón','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perdiguero Portugués','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Boyero de Appenzell','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Boyero de Entlebuch','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Agua Americano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de agua de Romagna','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Agua Irlandés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Agua Portugués','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Canaan','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Caza Polaco','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Osos de Carelia','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Pastor Catalán','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Pastor Portugués','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Taiwán','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Finlandés de Laponia','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Pastor Croata','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Sin Pelo del Perú','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Sueco de Laponia','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Tailandés con Cresta','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Tejonero de Westfalia','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pinscher Alemán','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pinscher Austríaco','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Podenco Ibicenco','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Porcelaine','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Puli','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Rastreador de Hannover','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Retriever de Nueva Escocia','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Alemán','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Anglo-Francés de Tamaño Mediano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Austríaco Negro y Fuego','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Bávaro de Montaña','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso de Bosnia (llamado Barak)','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso de Halden','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso de Hygen','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso de Istria de Pelo Corto','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso de Istria de Pelo Duro','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso de Montaña de Montenegro','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso de Posavatz','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso de Småland','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso del Tirol','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Eslovaco','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Español','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Estirio de Pelo Duro','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Finlandés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Helénico','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Italiano de Pelo Duro','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Italiano de Pelo Raso','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Noruego','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Schiller','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Serbio','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Suizo','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Tricolor Serbio','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Saluki','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Samoyedo','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Schapendoes Neerlandés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Schnauzer','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Setter Inglés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Setter Irlandés Rojo','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Setter Irlandés Rojo y Blanco','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Shar Pei','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Shikoku','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sloughi','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel Azul de Picardía','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel Bretón','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel de Campo','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel de Pont-Audemer','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel Francés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel Holandés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spitz Alemán','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spitz de Norrbotten','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spitz Finlandés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Springer Spaniel Galés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Springer Spaniel Inglés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Staffordshire Bull Terrier','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sussex Spaniel','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Irlandés','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Irlandés de Pelo Suave','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Tibetano','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Welsh Corgi Cardigan','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Welsh Corgi Pembroke','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Xoloitzcuintle','mediano','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Akita','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Akita Americano','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Antiguo Perro de Muestra Danés','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Antiguo Perro de Pastor Inglés','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Basset Hound','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Billy','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Borzoi','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bóxer','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Boyero de Flandes','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco Alemán de Pelo Corto','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco Francés - Tipo Gascuña','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco Húngaro de Pelo Duro','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Braco Italiano','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cane Corso Italiano','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Chesapeake Bay Retriever','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cimarrón Uruguayo','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Clumber Spaniel','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cobrador de Pelo Liso','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Curly Coated Retriever','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Dálmata','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Dogo Argentino','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Dogo Canario','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Espinone','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Fila de San Miguel','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Foxhound Inglés','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Galgo Español','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Galgo Inglés','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Golden Retriever','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gran Boyero Suizo','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gran Grifón Vendeano','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gran Munsterlander','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gran Sabueso Anglo-Francés Blanco y Naranja','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gran Sabueso Anglo-Francés Blanco y Negro','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gran Sabueso Anglo-Francés Tricolor','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gran Sabueso Azul de Gascuña','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Grifón de Muestra Bohemio de Pelo Duro','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Hovawart','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Komondor','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Kuvasz','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Labrador Retriever','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Lebrel Afgano','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Lebrel Escocés','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Lebrel Húngaro','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Otterhound','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Ovejero Alemán','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor Blanco Suizo','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor de Beauce','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor de Brie','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor Holandés','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pastor Polaco de Podhale','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perdiguero de Burgos','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perdiguero de Drente','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Cazador de Alces Sueco','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Crestado Rodesiano','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Agua Frisón','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Castro Laboreiro','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Groenlandia','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Montaña del Atlas','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Muestra Alemán de Pelo Cerdoso','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Muestra Alemán de Pelo Duro','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Muestra Alemán de Pelo Largo','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Pastor de la Maremma','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Pastor Mallorquín','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Pastor Rumano de los Cárpatos','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de San Huberto','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de San Huberto adulto para','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro del Faraón','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Dogo Mallorquín','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Lobo Checoslovaco','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Lobo de Saarloos','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Negro y Fuego para la Caza del Mapache','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro Pastor Rumano de Mioritza','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Podenco Canario','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pointer Inglés','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pudelpointer','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Rafeiro del Alentejo','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Artesiano','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Francés Blanco y Naranja','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Francés Blanco y Negro','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Francés Tricolor','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Hamilton','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Poitevin','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sabueso Polaco','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Schnauzer Gigante','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Setter Gordon','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Spaniel Picardo','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Tchuvatch Eslovaco','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terrier Negro Ruso','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Weimaraner','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Boyero de Berna','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Broholmer','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bullmastiff','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Dogo de Burdeos','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Dogo del Tíbet','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gran Danés','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Landseer','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Lebrel Irlandés','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Leonberger','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Mastiff','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Mastín del Pirineo','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Mastín Español','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Mastín Napolitano','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de la Sierra de la Estrela','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Montaña de los Pirineos','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Perro de Pastor Kangal','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Rottweiler','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('San Bernardo','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Terranova','grande','perro');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Abisinio','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('American Wirehair','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Americano de Pelo Corto','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Asiático','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Australian Mist','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Azul Ruso','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bengal','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bobtail Americano','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bombay','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Británico de Pelo Corto','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Burmés','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Burmilla','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cornish Rex','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Curl Americano','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Devon Rex','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Donskoy','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('German Rex','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Havana','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Korat','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Kurilian Bobtail','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Manx','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Mau Egipcio','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Munchkin','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Ocicat','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Ojos de Diamante','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Oriental','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Peterbald','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Pixiebob','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Seychellois','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Siamés','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Singapura','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Snowshoe','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sokoke','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sphynx','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Tonquinés','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Angora Turco','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Bobtail Japonés','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Chartreux','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Cymric','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Fold Escocés','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Gato de los Bosques de Noruega','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Laperm','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Maine Coon','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Neva Masquerade','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Ragamuffin','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Ragdoll','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Sagrado de Birmania','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Scottish Straight','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Selkirk Rex','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Somalí','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Van Turco','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Balinés','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Británico de Pelo Largo','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Persa','pequenio','gato');
INSERT INTO TipoAnimal(raza,tamanio,tipo) VALUES ('Siberiano','pequenio','gato');
